### ISSUE TITLE
yarn dist fails with exit code 1

### ISSUE THREAD

**Issue by moogsyn** [cryptofyre/Apple-Music-Electron#38]
"yarn dist" throws error
/home/wpd/Apple-Music-Electron/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                              Error: /home/wpd/Apple-Music-Electron/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                  at ChildProcess.<anonymous> (/home/wpd/Apple-Music-Electron/node_modules/builder-util/src/util.ts:243:14)
                                                                                                                                                  at Object.onceWrapper (events.js:422:26)
                                                                                                                                                  at ChildProcess.emit (events.js:315:20)
                                                                                                                                                  at maybeClose (internal/child_process.js:1048:16)
                                                                                                                                                  at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
error Command failed with exit code 1.

**Comment by moogsyn** [comment]
node version:14.16.1
electron version: 12.0.6
yarn version: 1.22.5
linux distro: elementary os 5.1 "hera"

**Comment by moogsyn** [comment]
update: installing "rpm" fixed it
